# Site settings
title: Modern Control Magic with Mike
description: >
  I am a casual magic player of 25 years who has
  converted to modern. In this blog, I talk specifically
  about my attempts to build and improve as a cotrol player
baseurl: ""
url: "http://slatron.github.io"
twitter_username: slatron
github_username:  slatron
plugins: [jekyll-paginate]
paginate: 5
port: 5000

# Build settings
markdown: kramdown
