# Site settings
title: Crosstronica Dev Blog
description: >
  This is the development blog of Mike Slater.
  For a cross-stitch helper app built
  with angular. Seriously
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://slatron.github.io"
twitter_username: slatron
github_username:  slatron
paginate: 5

# Build settings
markdown: kramdown
