# Site settings
title: slatronica music
subtitle: music by mike slater
description: >
  this is mike slater's music recording blog
baseurl: ""
url: "http://slatron.github.io"
reddit_username: slatron11
twitter_username: slatron
github_username:  slatron
plugins: [jekyll-paginate]
paginate: 18
port: 5000

# Build settings
markdown: kramdown
